// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmvfjogtzqsxrbrksbzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdmZqb2d0enFzeHJicmtzYnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODY1MTMsImV4cCI6MjA2NjM2MjUxM30.Fpf_RDtYi_L8c9fBPShBi-jAr6BU3eDVDDognqJPF1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);